version: "3"
services:
 app:
   container_name: edokyu
   restart: always
   build: .
   ports:
     - "80:80"
     - "443:443"
   links:
     - mongo
   volumes:
     - "./temp/drive:/drive"
     - ".:/edokyu"

 mongo:
   container_name: mongo
   image: mongo
   ports:
     - "27017:27017" 
   volumes:
     - "./data:/data/db"

    